version: '3'

services:
  db:
    # image: mysql:8.0.23
    image: mariadb:10.5.9
    restart: always
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: vsp
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  web:
    restart: always
    depends_on:
      - db
    volumes:
      # - /path/to/your/games.log:/vsp/games.log
      # - /path/to/your/server.gif:/vsp/pub/images/server.gif
      # - /path/to/your/logo.gif:/vsp/pub/images/logo.gif
      - ./osp.log:/vsp/games.log
      - logdata:/vsp/logdata
    ports:
      - 80:80
      # supervisor web gui would be available on port 9001
      # - 9001:9001
    environment:
      TZ: Europe/Berlin
      # VSP_WEB_PASSWORD: vspweb
      DB_NAME: vsp
      DB_USERNAME: devuser
      DB_PASSWORD: devpass
volumes:
  logdata:
