# docker-compose -p vsp up -d --build

version: '3'

services:
  db:
    # image: mysql:8.0.23
    image: mariadb:10.5.9
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: vsp
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./..:/var/www/html/
    ports:
      - 80:80
    environment:
      #xdebug 2
      # XDEBUG_CONFIG: remote_enable=1 remote_autostart=1 default_enable=1 remote_host=host.docker.internal idekey=VSCODE remote_port=9000
      #xdebug 3
      # discover_client_host=true
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: start_with_request=yes client_port=9003 idekey=VSCODE client_host=host.docker.internal
